In [1]:
import tensorflow as tf

2024-09-04 06:57:42.261386: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-04 06:57:42.261533: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-04 06:57:43.599574: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-04 06:57:46.186349: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-04 06:57:52.903970: W tensorflow/comp

In [2]:
from tensorflow import keras

In [3]:
imdb = keras.datasets.imdb

In [4]:
dir(imdb)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'get_word_index',
 'load_data']

In [5]:
dictionary = imdb.get_word_index()

1641221/1641221 [==============================] - 0s 0us/step


In [6]:
data = imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [7]:
data

((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

In [8]:
len(data)

2

In [9]:
len(data[0]), len(data[1])

(2, 2)

In [10]:
data[0][0]

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [11]:
data[0][1]

array([1, 0, 0, ..., 0, 1, 0])

In [12]:
data[1][0]

array([list([1, 591, 202, 14, 31, 6, 717, 10, 10, 18142, 10698, 5, 4, 360, 7, 4, 177, 5760, 394, 354, 4, 123, 9, 1035, 1035, 1035, 10, 10, 13, 92, 124, 89, 488, 7944, 100, 28, 1668, 14, 31, 23, 27, 7479, 29, 220, 468, 8, 124, 14, 286, 170, 8, 157, 46, 5, 27, 239, 16, 179, 15387, 38, 32, 25, 7944, 451, 202, 14, 6, 717]),
       list([1, 14, 22, 3443, 6, 176, 7, 5063, 88, 12, 2679, 23, 1310, 5, 109, 943, 4, 114, 9, 55, 606, 5, 111, 7, 4, 139, 193, 273, 23, 4, 172, 270, 11, 7216, 10626, 4, 8463, 2801, 109, 1603, 21, 4, 22, 3861, 8, 6, 1193, 1330, 10, 10, 4, 105, 987, 35, 841, 16873, 19, 861, 1074, 5, 1987, 17975, 45, 55, 221, 15, 670, 5304, 526, 14, 1069, 4, 405, 5, 2438, 7, 27, 85, 108, 131, 4, 5045, 5304, 3884, 405, 9, 3523, 133, 5, 50, 13, 104, 51, 66, 166, 14, 22, 157, 9, 4, 530, 239, 34, 8463, 2801, 45, 407, 31, 7, 41, 3778, 105, 21, 59, 299, 12, 38, 950, 5, 4521, 15, 45, 629, 488, 2733, 127, 6, 52, 292, 17, 4, 6936, 185, 132, 1988, 5304, 1799, 488, 2693, 47, 6, 392, 173, 4, 21686, 4

In [13]:
data[1][1]

array([0, 1, 1, ..., 0, 0, 0])

In [14]:
(xtrain,ytrain), (xtest,ytest) = data 

In [15]:
ytrain[:5]

array([1, 0, 0, 1, 0])

In [16]:
ytest[:5]

array([0, 1, 1, 0, 1])

In [17]:
# 0 -> PADDING 
# 1 -> START
# 2 -> UNKNOWN -> it doesn't exist in my dictionary 
# 3 -> UNUSED 

In [20]:
dictionary

{'fawn': 34701,
 'tsukino': 52006,
 'nunnery': 52007,
 'sonja': 16816,
 'vani': 63951,
 'woods': 1408,
 'spiders': 16115,
 'hanging': 2345,
 'woody': 2289,
 'trawling': 52008,
 "hold's": 52009,
 'comically': 11307,
 'localized': 40830,
 'disobeying': 30568,
 "'royale": 52010,
 "harpo's": 40831,
 'canet': 52011,
 'aileen': 19313,
 'acurately': 52012,
 "diplomat's": 52013,
 'rickman': 25242,
 'arranged': 6746,
 'rumbustious': 52014,
 'familiarness': 52015,
 "spider'": 52016,
 'hahahah': 68804,
 "wood'": 52017,
 'transvestism': 40833,
 "hangin'": 34702,
 'bringing': 2338,
 'seamier': 40834,
 'wooded': 34703,
 'bravora': 52018,
 'grueling': 16817,
 'wooden': 1636,
 'wednesday': 16818,
 "'prix": 52019,
 'altagracia': 34704,
 'circuitry': 52020,
 'crotch': 11585,
 'busybody': 57766,
 "tart'n'tangy": 52021,
 'burgade': 14129,
 'thrace': 52023,
 "tom's": 11038,
 'snuggles': 52025,
 'francesco': 29114,
 'complainers': 52027,
 'templarios': 52125,
 '272': 40835,
 '273': 52028,
 'zaniacs': 52130,

In [21]:
dictionary["hello"]

4822

In [22]:
dictionary["sandwich"]

15457

In [30]:

rev_dic = { v:k for k,v in dictionary.items() }

In [31]:
rev_dic[68948]

'nonmoving'

In [32]:
def decoder(sentence):
    return " ".join([ rev_dic[word] for word in sentence])

In [35]:
decoder(xtrain[142])

'the go was story why was use of ever was nature back used money or no was how least perkins was just has businessmen was nature in same back camera of dialogue br ova engagingly was rather his woman what that it part are states not was one in why was people just of ever to go was then rents that movie is ursula ever that it time tony to was people just of recommended may of films movie much s of television down i i was story itself why for that it him in can sane inventive those are of goes most was had several made this myself feel was me other life of found like effects charecters under this members to go was two for with so believable ever was people his had just about being this as ever most evil out his only melodramatic br denzel not would pressed that some around much'

In [36]:
rev_dic[1] # should have been <START>

'the'

In [37]:
rev_dic[2] # should have been <UNKNOWN>

'and'

In [38]:
rev_dic[3] # should have been <UNUSED>

'a'

In [39]:
rev_dic[0] # should exist, and should be <PAD>

KeyError: 0

In [41]:
new_dic = { word:idx+3 for word,idx in dictionary.items()}

In [42]:
new_dic["<PAD>"] = 0
new_dic["<START>"] = 1
new_dic["<UNK>"] = 2
new_dic["<UNUSED>"] = 3

In [43]:
rev_new_dic = { v:k for k,v in new_dic.items()}

In [44]:
def new_decoder(sentence):
    return " ".join([ rev_new_dic[word] for word in sentence])

In [48]:
ytrain[42]

0

In [45]:
new_decoder(xtrain[42])

"<START> warning this review contains spoilers do not read if you don't want some points revealed to you before you watch the film br br with a cast like this you wonder whether or not the actors and actresses knew exactly what they were getting into did they see the script and say hey close encounters of the third kind was such a hit that this one can't fail ' unfortunately it does did they even think to check on the director's credentials i mean would you do a movie with the director of a movie called satan's cheerleaders ' greydon clark who would later go on to direct the infamous final justice ' made this it makes you wonder how the people of mystery science theater 3000 could hammer final justice' and completely miss out on the return ' br br the film is set in a small town in new mexico a little boy and girl are in the street unsupervised one night when a powerful flashlight beam er a spaceship appears and hovers over them in probably the worst special effect sequence of the film

In [46]:
new_decoder(xtrain[20])

"<START> shown in australia as 'hydrosphere' this incredibly bad movie is so bad that you become hypnotised and have to watch it to the end just to see if it could get any worse and it does the storyline is so predictable it seems written by a high school dramatics class the sets are pathetic but marginally better than the miniatures and the acting is wooden br br the infant 'muppet' seems to have been stolen from the props cupboard of 'total recall' there didn't seem to be a single original idea in the whole movie br br i found this movie to be so bad that i laughed most of the way through br br malcolm mcdowell should hang his head in shame he obviously needed the money"

In [47]:
ytrain[20]

0

In [49]:
for i in range(10): # Reviews are NOT of same size!
    print(len(xtrain[i]))

218
189
141
550
147
43
123
562
233
130


In [ ]:
# since all of them are of diff sizes, a neural network cannot accept all of them!
# modify our sentences such that:
# large sentences -> CHOP THEM OFF
# small sentences -> Fill them up with 0!

In [56]:
HP_MAX_LEN = 256


In [57]:
xtrain_padded = keras.utils.pad_sequences(xtrain, 
                                         maxlen=HP_MAX_LEN, 
                                         padding='post',
                                         truncating='post',
                                         )

In [62]:
xtrain_padded[142]

array([    1,   137,    13,    62,   135,    13,   358,     4,   123,
          13,   873,   142,   340,   275,    39,    54,    13,    86,
         219, 10617,    13,    40,    44, 15149,    13,   873,     8,
         169,   142,   367,     4,   411,     7, 17690, 29191,    13,
         244,    24,   252,    48,    12,     9,   170,    23,  1627,
          21,    13,    28,     8,   135,    13,    81,    40,     4,
         123,     5,   137,    13,    92, 12371,    12,    17,     6,
        9019,   123,    12,     9,    55,  1220,     5,    13,    81,
          40,     4,  1175,   200,     4,   105,    17,    73,   587,
           4,   696,   177,    10,    10,    13,    62,   407,   135,
          15,    12,     9,    87,     8,    67,  7918,  4409,   145,
          23,     4,   268,    88,    13,    66,   447,    90,    11,
         543,   232,    13,    69,    82,   110,     4,   255,    37,
         299, 38354,   464,    11,  1063,     5,   137,    13,   104,
          15,    16,

In [63]:
new_decoder(xtrain_padded[142])

"<START> while i would say i enjoy the show i expected something completely different from when i first saw 'what i like about you' i expected to find something along the lines of 'all that' i am not sure if it is going on anymore but i have to say i do like the show and while i don't classify it as a breakthrough show it is very charming and i do like the chemistry between the characters as well including the supporting cast br br i would definitely say that it is great to see wesley jonathan back on the screen because i really loved him in city guy i had also seen the woman who plays valerie's friend in popular and while i think that was an okay show i do not really like her character in this show because she's just not my cup of tea but she rounds it out pretty well <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD

In [64]:
for i in range(10): # Reviews are NOT of same size!
    print(len(xtrain_padded[i]))

256
256
256
256
256
256
256
256
256
256


In [65]:
# just like training data, we should also process the testing data

xtest_padded = keras.utils.pad_sequences(xtest, 
                                         maxlen=HP_MAX_LEN, 
                                         padding='post',
                                         truncating='post',
                                         )

In [66]:
# PATTERN DETECTION -> at least one input layer, output layer, and at least 1  HIDDEN LAYER

# these layers, also known as FULLY CONNECTED LAYERS or DENSE LAYERS accept only sequential numbers

# NLP PROBLEM -> EMBEDDING -> our words as numbers will be converted into multi-dimensional vectors

# sentence length of 100, and a total of 1000 possible english words
# for every word, at every position, i will generate a vector matrix 

# i am the batman
# the batman is hungry
# hunger is batman 

# with 4 positions and 4 words   -> This matrix is Created by EMBEDDING LAYER
#.      pos1 pos2 pos3 pos4
# word1  v1.  v2.  v3   v4
# word2  v5.  v6.  v7.  v8
# word3  v9.  v10. v11. v12
# word4  v13  v14  v15  v16

# But dense layers do not accept matrix, they accept only linear numbers!

# we need a way in which this matrix should convert into a single line of vectors!

# just calculate average of all the vectors!

# OVERALL NETWORK NOW LOOKS LIKE->

# Embedding Layer -> GlobalAveragePooling1D -> Pattern_Recognition
# Embedding Layer -> GlobalAveragePooling1D -> (Dense Layers) X 3



In [97]:
l1 = keras.layers.Embedding(10000, 32)  # number of parameters = 10k X 32
l2 = keras.layers.GlobalAveragePooling1D() # number of parameters = 0
l3 = keras.layers.Dense(64, activation='relu') # in order to move away from straight lines, 
l4 = keras.layers.Dense(128, activation='relu') # we need to use 'ACTIVATION FUNCTIONS'
l5 = keras.layers.Dense(1, activation = 'sigmoid')

# relu -> removes all negative numbers from input
# sigmoid -> single probability, between 0 to 1
# softmax -> converts results into proabability distribution 

In [98]:
model = keras.Sequential([l1,l2, l3, l4, l5])
model.compile(loss='binary_crossentropy' , optimizer='adam')

In [94]:
model.fit(xtrain_padded, ytrain, epochs=20)

Epoch 1/20


ValueError: in user code:

    File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.9/site-packages/keras/src/engine/training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.9/site-packages/keras/src/engine/training.py", line 1384, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.9/site-packages/keras/src/engine/training.py", line 1373, in run_step  **
        outputs = model.train_step(data)
    File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.9/site-packages/keras/src/engine/training.py", line 1151, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.9/site-packages/keras/src/engine/training.py", line 1209, in compute_loss
        return self.compiled_loss(
    File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.9/site-packages/keras/src/engine/compile_utils.py", line 277, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.9/site-packages/keras/src/losses.py", line 143, in __call__
        losses = call_fn(y_true, y_pred)
    File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.9/site-packages/keras/src/losses.py", line 270, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.9/site-packages/keras/src/losses.py", line 2532, in binary_crossentropy
        backend.binary_crossentropy(y_true, y_pred, from_logits=from_logits),
    File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.9/site-packages/keras/src/backend.py", line 5822, in binary_crossentropy
        return tf.nn.sigmoid_cross_entropy_with_logits(

    ValueError: `logits` and `labels` must have the same shape, received ((None, 2) vs (None, 1)).


In [78]:
# problem-> too many words which neural network cannot figure out within its 10,000 limit!
# solution -> read your data only considering the top 10,000 words!
# rest of the words will become UNKNOWN for us, which is handled by using 2
data = imdb.load_data(num_words=10000)

In [79]:
# let's do the entire processing again only considering the top 10k words

(xtrain,ytrain), (xtest, ytest) = data
xtrain_padded = keras.utils.pad_sequences(xtrain, 
                                         maxlen=HP_MAX_LEN, 
                                         padding='post',
                                         truncating='post',
                                         )
xtest_padded = keras.utils.pad_sequences(xtest, 
                                         maxlen=HP_MAX_LEN, 
                                         padding='post',
                                         truncating='post',
                                         )

In [99]:
model.fit(xtrain_padded, ytrain, epochs=20)

Epoch 1/20
782/782 [==============================] - 4s 4ms/step - loss: 0.3911
Epoch 2/20
782/782 [==============================] - 3s 4ms/step - loss: 0.2252
Epoch 3/20
782/782 [==============================] - 3s 4ms/step - loss: 0.1768
Epoch 4/20
782/782 [==============================] - 3s 4ms/step - loss: 0.1450
Epoch 5/20
782/782 [==============================] - 3s 3ms/step - loss: 0.1272
Epoch 6/20
782/782 [==============================] - 3s 4ms/step - loss: 0.1128
Epoch 7/20
782/782 [==============================] - 3s 4ms/step - loss: 0.0971
Epoch 8/20
782/782 [==============================] - 3s 4ms/step - loss: 0.0853
Epoch 9/20
782/782 [==============================] - 3s 3ms/step - loss: 0.0747
Epoch 10/20
782/782 [==============================] - 3s 4ms/step - loss: 0.0602
Epoch 11/20
782/782 [==============================] - 3s 4ms/step - loss: 0.0502
Epoch 12/20
782/782 [==============================] - 3s 4ms/step - loss: 0.0459
Epoch 13/20
782/782 [====

In [100]:
p = model.predict(xtest_padded)

782/782 [==============================] - 1s 1ms/step


In [101]:
p[0] # first prediction, corresponding to ytest[0]

array([0.00046709], dtype=float32)

In [102]:
ytest[0]

0

In [103]:
p[:10]

array([[4.6709157e-04],
       [1.0000000e+00],
       [1.5500232e-03],
       [9.9595743e-01],
       [9.9999392e-01],
       [9.9921578e-01],
       [9.9975306e-01],
       [4.7539186e-07],
       [9.9999833e-01],
       [9.9991924e-01]], dtype=float32)

In [104]:
classifier = lambda val: 1 if val>0.5 else 0
prob = [ classifier(result) for result in p]

In [105]:
prob[:10]

[0, 1, 0, 1, 1, 1, 1, 0, 1, 1]

In [106]:
ytest[:10]

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1])

In [107]:
correct = 0
wrong = 0

for i in range(len(ytest)):
    if(prob[i] == ytest[i]):
        correct = correct+1
    else:
        wrong = wrong + 1

In [108]:
correct, wrong

(20790, 4210)

In [109]:
# accuracy = correct_guesses / total guesses

acc = correct / (correct + wrong)
acc

0.8316